version: "3.9"
services:
    nestify:
        container_name: nestify
        env_file: "env/.env.${ENV}"
        build:
            context: .
            dockerfile: ./docker/dev.Dockerfile
        image: nestify
        depends_on:
            - traefik
            - redis
            - rabbitmq
        restart: unless-stopped
        command: "npm run start:dev"
        labels:
            - traefik.enable=true
            - traefik.http.routers.nestify.rule=Host(`api.takeodev.ml`)
            - traefik.http.services.nestify.loadbalancer.server.port=8000
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true
        networks:
            - nestify-network
        volumes:
            - ".:/usr/src/app"
            - /usr/src/app/node_modules
    traefik:
        image: "traefik:v2.9.6"
        container_name: traefik
        command:
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--accesslog"
            - "--log"
            - "--api"
            - "--api.insecure=true"
        labels:
            - traefik.enable=true
        networks:
            - nestify-network
        ports:
            - "443:443"
            - "80:80"
            - "8080:8080"
        volumes:
            - "./letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
    redis:
        image: "redis:7.0.7-alpine"
        restart: always
        ports:
            - "6379"
        networks:
            - nestify-network
        command: "redis-server --loglevel warning --requirepass ${PASSWORD}"
        volumes:
            - "redis-data:/data"
    rabbitmq:
        container_name: rabbitmq
        image: "rabbitmq:3.11.5-management-alpine"
        networks:
            - nestify-network
        environment:
            - RABBITMQ_DEFAULT_USER=nestify
            - "RABBITMQ_DEFAULT_PASS=${PASSWORD}"
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - "rabbitmq-data:/var/lib/rabbitmq/mnesia/"
    db:
        image: "postgres:14.1-alpine"
        restart: unless-stopped
        volumes:
            - "postgres_data:/var/lib/postgresql/data/"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=somesecretpassword
            - POSTGRES_DB=postgres
        networks:
            - nestify-network
    pgadmin:
        container_name: pgadmin4_container
        image: "dpage/pgadmin4:5.5"
        restart: unless-stopped
        environment:
            - PGADMIN_DEFAULT_EMAIL: admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD: secret
            - PGADMIN_LISTEN_PORT: 80
        ports:
            - "8090:80"
        volumes:
            - "pgadmin-data:/var/lib/pgadmin"
        networks:
            - nestify-network
volumes:
    redis-data: null
    rabbitmq-data: null
    postgres_data: null
    pgadmin-data: null
networks:
    nestify-network:
        name: nestify-network
