version:
    "3.9"

    #######################################
    # Basic needed services
    #######################################

services:
    nest-app:
        container_name: nest-app
        env_file: "env/.env.${ENV}"
        build:
            context: "."
            dockerfile: ./Dockerfile
        image: nest-app
        depends_on:
            - redis
            - db
            - minio
        restart: unless-stopped
        ports:
            - "8000:8000"

    redis:
        image: redis:7.0.4-alpine
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes:
            - redis-data:/data

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypassword
        ports:
            # AMQP protocol port
            - "5672:5672"
            # HTTP management UI
            - "15672:15672"

    minio:
        image: minio/minio:RELEASE.2020-11-10T21-02-24Z
        container_name: minio
        hostname: minio
        restart: unless-stopped
        volumes:
            - minio:/data
        ports:
            - "4090:9000"
        env_file: "env/.env.${ENV}"
        entrypoint: sh
        command: -c 'mkdir -p /export/default-bucket && /usr/bin/minio server /export'
        healthcheck:
            test:
                ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

volumes:
    redis-data:
    db:
    minio:
