version:
    "3.9"

    #######################################
    # Basic needed services
    #######################################

services:
    nestify:
        container_name: nestify
        env_file: "env/.env.${ENV}"
        build:
            context: "."
            dockerfile: ./docker/dev.Dockerfile
        image: nestify
        depends_on:
            - traefik
            - redis
            - rabbitmq
        restart: unless-stopped
        command: npm run start:dev
        labels:
            - "traefik.http.routers.nestify.rule=Host(`api.example.com`)"
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true
        networks:
            - nestify-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules

 traefik:
    image: traefik:v2.9
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--log.LEVEL=DEBUG"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
    networks:
      - nestify-network
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    redis:
        image: redis:7.0.7-alpine
        restart: always
        ports:
            - "6379:6379"
        networks:
            - nestify-network
        command: redis-server --loglevel warning --requirepass ${PASSWORD}
        volumes:
            - redis-data:/data

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.11.5-management-alpine
        networks:
            - nestify-network
        environment:
            - RABBITMQ_DEFAULT_USER=nestify
            - RABBITMQ_DEFAULT_PASS=${PASSWORD}
        ports:
            # AMQP protocol port
            - "5672:5672"
            # HTTP management UI
            - "15672:15672"
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq/mnesia/

volumes:
    redis-data:
    rabbitmq-data:

networks:
  nestify-network:
    name: nestify-network
