name: CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [18.x,19.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install pnpm and npm
            - run: |
                curl -L https://get.pnpm.io/v6.js | node - add --global pnpm
            - run: pnpm install --shamefully-hoist=true
            - run: pnpm run lint
              env:
                  CI: true
